name: reddit_2_video
description: A command-line application for generating a tiktok-style reddit commentary video.
version: 1.0.0
repository: https://github.com/Thomasssb1/reddit-bot

environment:
  sdk: ">=3.0.0"

executables:
  reddit-2-video: reddit-2-video

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.5
dependencies:
  args: ^2.4.2
  deep_pick: ^1.0.0
  http: ^1.0.0
  remove_emoji: ^0.0.10
  path: ^1.8.3
  youtube_explode_dart: ^2.0.3
