name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release
          github-token: ${{ github.token }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify Dart formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Verify Prettier formatting
        run: npx --yes prettier --check . --ignore-unknown

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

  coverage:
    needs: build
    uses: ./.github/workflows/coverage.yml
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
